name: CI/CD
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  verify-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | podman login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build Podman image
        run: |
          podman build \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/portfoliowebsitebuilder:${{ github.sha }} .
      - name: Run ESLint
        run: podman run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/portfoliowebsitebuilder:${{ github.sha }} npm run lint
      - name: Push Podman image
        run: |
          podman tag ${{ secrets.DOCKER_HUB_USERNAME }}/portfoliowebsitebuilder:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/portfoliowebsitebuilder:latest
          podman push ${{ secrets.DOCKER_HUB_USERNAME }}/portfoliowebsitebuilder:${{ github.sha }}
          podman push ${{ secrets.DOCKER_HUB_USERNAME }}/portfoliowebsitebuilder:latest

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
